`timescale 1ns / 1ps

//============================================================================
// MODULE: testbench
//============================================================================
// DESCRIPTION:
//   Directed Self-Checking Testbench for APB Master-Slave System
//
//   This testbench uses DIRECTED tests - specific, predetermined test cases
//   that are carefully crafted to verify specific functionality of the DUT.
//
// COMPATIBILITY:
//   - Fully compatible with Icarus Verilog (iverilog)
//   - No SystemVerilog features used
//   - Uses only Verilog-2001 constructs
//   - Tested with iverilog -g2009 flag
//
// VERIFICATION APPROACH:
//   - Directed Tests: Specific test cases with known expected results
//   - Self-Checking: Automatic pass/fail determination
//   - Reference Model: Golden memory model for comparison
//   - Scoreboard: Statistics tracking
//   - Transaction History: Full transaction recording
//
// TEST ORGANIZATION:
//   - Test Group 1: Basic Functionality (Write, Read, Write-Read)
//   - Test Group 2: Error & Boundary Conditions
//   - Test Group 3: Stress & Corner Cases
//   - Test Group 4: Reset Recovery
//   - Test Group 5: Performance Measurement
//
// COMPILATION:
//   iverilog -o apb_sim -g2009 APB_slave.v APB_master.v APB_top.v testbench.v
//   vvp apb_sim
//
// WAVEFORM:
//   gtkwave apb_sim.vcd
//============================================================================
module testbench;

    //========================================================================
    // VERIFICATION PARAMETERS
    //========================================================================
    // These parameters control the testbench behavior.
    // They can be modified to change the test conditions without
    // altering the core test logic.
    //========================================================================
    
    parameter CLK_PERIOD    = 10;        // Clock period in ns (100 MHz)
    parameter TIMEOUT_CYCLES = 20;       // Max wait cycles for PREADY
    parameter DEBUG_LEVEL   = 1;         // 0=Minimal, 1=Normal, 2=Verbose
    parameter READ_PIPELINE_DELAY = 2;    // Pipeline stages for read data

    //========================================================================
    // CLOCK AND RESET SIGNALS
    //========================================================================
    // These signals drive the DUT clock and reset inputs.
    // - pclk: Free-running clock generated by testbench
    // - presetn: Active-low reset controlled by test sequence
    //========================================================================
    
    reg pclk;              // APB Clock - generated by testbench
    reg presetn;           // Active-low asynchronous reset

    //========================================================================
    // DUT INPUT DRIVERS - Stimulus Generation
    //========================================================================
    // These signals drive the DUT's user interface.
    // They are controlled by the test helper tasks (write_test, read_test).
    //========================================================================
    
    reg transfer;                  // Transfer request from user logic
    reg read;                      // Read operation request
    reg write;                     // Write operation request
    reg [7:0] apb_write_paddr;     // Write address from user
    reg [7:0] apb_write_data;      // Write data from user
    reg [7:0] apb_read_paddr;      // Read address from user

    //========================================================================
    // DUT OUTPUT MONITORS - Response Capture
    //========================================================================
    // These signals capture the DUT outputs for verification.
    // They are compared against the reference model in the scoreboard.
    //========================================================================
    
    wire        pslverr;            // Aggregated slave error indicator
    wire [7:0]  apb_read_data_out;  // Read data returned to user

    //========================================================================
    // INTERNAL SIGNAL TAPS - Protocol Monitoring
    //========================================================================
    // These signals provide visibility into the DUT's internal signals.
    // They are used for protocol checking and debugging.
    //========================================================================
    
    wire        penable;        // ENABLE phase indicator
    wire        pwrite;         // Write/Read control
    wire        psel1, psel2;   // Slave select signals
    wire [7:0]  paddr;          // Address bus
    wire [7:0]  pwdata;         // Write data bus
    wire        pready;         // Transfer completion signal
    wire [7:0]  prdata_mux;     // Muxed read data

    //========================================================================
    // SCOREBOARD / REFERENCE MODEL
    //========================================================================
    // This section implements the golden reference model that mirrors
    // the DUT's memory behavior. All DUT outputs are compared against
    // this model to determine pass/fail.
    //
    // The reference model is a simple 256-byte memory array that mirrors
    // the DUT slave1 memory (addresses 0x00-0x7F are valid).
    //========================================================================
    
    //------------------------------------------------------------------------
    // Reference Memory
    //------------------------------------------------------------------------
    // Golden reference model - mirrors DUT slave1 memory
    // Used for read data verification
    //------------------------------------------------------------------------
    reg [7:0] ref_memory [0:255];   // Reference memory (256 bytes)
    integer idx;                     // Loop counter for initialization
    
    //------------------------------------------------------------------------
    // Scoreboard Statistics
    //------------------------------------------------------------------------
    // These counters track the verification progress and results.
    // They are used in the final report.
    //------------------------------------------------------------------------
    integer score_pass;          // Number of passing tests
    integer score_fail;          // Number of failing tests
    integer score_total;         // Total tests executed
    integer score_warnings;      // Number of protocol warnings
    
    //------------------------------------------------------------------------
    // Transaction History
    //------------------------------------------------------------------------
    // These arrays store detailed information about every transaction.
    // Used for debugging and failure analysis.
    //
    // Icarus Note: We use separate arrays instead of SystemVerilog structs.
    //------------------------------------------------------------------------
    reg [0:255] trans_pwrite;        // Operation type (1=Write, 0=Read)
    reg [7:0]   trans_paddr [0:255]; // Address accessed
    reg [7:0]   trans_pwdata [0:255];// Write data
    reg [7:0]   trans_prdata [0:255];// Read data
    reg [0:255] trans_pslverr;       // Error status
    reg [0:255] trans_passed;        // Test result (1=Pass, 0=Fail)
    reg [0:255] trans_checked;       // Whether transaction was verified
    integer trans_index;             // Current history index
    
    //------------------------------------------------------------------------
    // Current Transaction Tracking
    //------------------------------------------------------------------------
    // Temporary storage for the transaction being processed.
    //------------------------------------------------------------------------
    reg current_pwrite;
    reg [7:0] current_paddr;
    reg [7:0] current_pwdata;
    reg [7:0] current_prdata;
    reg current_pslverr;
    reg current_passed;
    reg current_checked;

    //========================================================================
    // READ PIPELINE TRACKING - Delayed Verification
    //========================================================================
    // The APB master has a 2-cycle pipeline for read data (see RTL).
    // These signals track pending reads through the pipeline and
    // verify data at the correct time.
    //
    // This is CRITICAL for correct read verification.
    //========================================================================
    
    reg [1:0] pipeline_cnt;          // Pipeline stage counter
    reg       read_pending;          // Flag indicating pending read
    reg [7:0] pending_addr;          // Address of pending read
    reg [7:0] pending_data;          // Expected data for pending read
    reg       pending_check_done;    // Flag indicating check completed

    //========================================================================
    // FSM STATE TRACKING - Protocol Monitoring
    //========================================================================
    // These signals track the APB master FSM state for protocol checking.
    // The IDLE detection is debounced to prevent false warnings.
    //========================================================================
    
    reg [1:0] master_state_reg;      // Registered master state (debounced)
    reg       idle_stable;           // Flag indicating stable IDLE state
    integer   idle_count;            // Counter for IDLE debouncing
    
    wire [1:0] master_state_comb;    // Combinational master state (immediate)
    
    //------------------------------------------------------------------------
    // FSM State Constants (must match RTL)
    //------------------------------------------------------------------------
    localparam IDLE   = 2'b00;       // IDLE state
    localparam SETUP  = 2'b01;       // SETUP state
    localparam ENABLE = 2'b10;       // ENABLE state

    //========================================================================
    // LOGGING SYSTEM - Icarus Compatible
    //========================================================================
    // This section implements a configurable logging system with
    // severity levels. The verbosity is controlled by DEBUG_LEVEL.
    //
    // Severity Levels:
    //   LOG_ERROR   (1) : Critical errors - always displayed
    //   LOG_WARNING (2) : Protocol warnings - displayed at level 0+
    //   LOG_INFO    (3) : Informational - displayed at level 1+
    //   LOG_DEBUG   (4) : Debug info - displayed at level 2+
    //
    // Icarus Note: We use `define macros for severity levels.
    //========================================================================
    
    `define LOG_ERROR   1
    `define LOG_WARNING 2
    `define LOG_INFO    3
    `define LOG_DEBUG   4
    
    //------------------------------------------------------------------------
    // Logging Task
    //------------------------------------------------------------------------
    // Displays a message with appropriate severity and verbosity control.
    // Uses color-coded icons for visual clarity.
    //------------------------------------------------------------------------
    task log_message;
        input integer severity;      // Severity level
        input string msg;            // Message string
        begin
            if (severity == `LOG_ERROR) begin
                // Errors are always displayed
                $display("[%0t] ❌ ERROR: %s", $time, msg);
            end
            else if (severity == `LOG_WARNING) begin
                // Warnings displayed at DEBUG_LEVEL >= 0
                if (DEBUG_LEVEL >= 0)
                    $display("[%0t] ⚠️  WARNING: %s", $time, msg);
            end
            else if (severity == `LOG_INFO) begin
                // Info displayed at DEBUG_LEVEL >= 1
                if (DEBUG_LEVEL >= 1)
                    $display("[%0t] ℹ️  INFO: %s", $time, msg);
            end
            else if (severity == `LOG_DEBUG) begin
                // Debug displayed at DEBUG_LEVEL >= 2
                if (DEBUG_LEVEL >= 2)
                    $display("[%0t] 🔍 DEBUG: %s", $time, msg);
            end
        end
    endtask

    //========================================================================
    // CLOCK GENERATION
    //========================================================================
    // Generates a free-running clock with period = CLK_PERIOD.
    // The clock starts at 0 and toggles every CLK_PERIOD/2 ns.
    //
    // Default: 100 MHz (10 ns period)
    //========================================================================
    
    initial begin
        pclk = 0;
        forever #(CLK_PERIOD/2) pclk = ~pclk;
    end

    //========================================================================
    // DUT INSTANTIATION
    //========================================================================
    // Instantiates the APB_top module (Device Under Test).
    // Connects all testbench signals to the DUT ports.
    //========================================================================
    
    APB_top dut (
        .pclk(pclk),
        .presetn(presetn),
        .transfer(transfer),
        .read(read),
        .write(write),
        .apb_write_paddr(apb_write_paddr),
        .apb_write_data(apb_write_data),
        .apb_read_paddr(apb_read_paddr),
        .pslverr(pslverr),
        .apb_read_data_out(apb_read_data_out)
    );

    //========================================================================
    // SIGNAL TAPS - Internal Signal Monitoring
    //========================================================================
    // Taps into the DUT's internal signals for protocol monitoring.
    // These assignments provide testbench access to internal signals.
    //========================================================================
    
    assign penable    = dut.penable;
    assign pwrite     = dut.pwrite;
    assign paddr      = dut.paddr;
    assign pwdata     = dut.pwdata;
    assign psel1      = dut.psel1;
    assign psel2      = dut.psel2;
    assign pready     = dut.pready_internal;
    assign prdata_mux = dut.prdata_mux;
    assign master_state_comb = dut.master_inst.state;

    //========================================================================
    // SCOREBOARD INITIALIZATION
    //========================================================================
    // Initializes all scoreboard statistics and transaction history.
    // Runs once at time 0.
    //========================================================================
    
    initial begin
        // Initialize scoreboard statistics
        score_pass = 0;
        score_fail = 0;
        score_total = 0;
        score_warnings = 0;
        trans_index = 0;
        
        // Initialize transaction history arrays
        for (idx = 0; idx < 256; idx = idx + 1) begin
            trans_pwrite[idx] = 1'b0;
            trans_paddr[idx] = 8'h00;
            trans_pwdata[idx] = 8'h00;
            trans_prdata[idx] = 8'h00;
            trans_pslverr[idx] = 1'b0;
            trans_passed[idx] = 1'b0;
            trans_checked[idx] = 1'b0;
        end
    end

    //========================================================================
    // DEBOUNCED IDLE DETECTION
    //========================================================================
    // Monitors the APB master FSM state and provides a debounced
    // IDLE detection signal. This prevents false warnings due to
    // metastability or glitches in state detection.
    //
    // How it works:
    //   - master_state_reg tracks the DUT state (1 cycle delay)
    //   - When state is IDLE for 3 consecutive cycles, idle_stable=1
    //   - This debouncing ensures reliable IDLE detection
    //========================================================================
    
    always @(posedge pclk or negedge presetn) begin
        if (!presetn) begin
            master_state_reg <= IDLE;
            idle_stable <= 1'b0;
            idle_count <= 0;
        end
        else begin
            // Register the current DUT state
            master_state_reg <= dut.master_inst.state;
            
            // Debounce IDLE detection (3 stable cycles)
            if (master_state_reg == IDLE) begin
                if (idle_count < 3) begin
                    idle_count <= idle_count + 1;
                    idle_stable <= 1'b0;
                end
                else begin
                    idle_stable <= 1'b1;  // Stable IDLE detected
                end
            end
            else begin
                idle_count <= 0;           // Reset counter if not IDLE
                idle_stable <= 1'b0;
            end
        end
    end

    //========================================================================
    // REFERENCE MODEL UPDATE
    //========================================================================
    // Updates the golden reference model on every valid write transaction.
    // This mirrors the DUT's memory behavior.
    //
    // The reference model is used for:
    //   - Read data verification (compare DUT output vs reference)
    //   - Scoreboard comparison (detect DUT errors)
    //========================================================================
    
    always @(posedge pclk or negedge presetn) begin
        if (!presetn) begin
            // Initialize reference memory on reset
            for (idx = 0; idx < 256; idx = idx + 1)
                ref_memory[idx] <= 8'h00;
        end
        else begin
            // Update reference on valid write transactions
            if (penable && pready && !pslverr) begin
                if (pwrite && paddr < 8'h80) begin
                    // Store write data in reference memory
                    ref_memory[paddr] <= pwdata;
                    log_message(`LOG_DEBUG, $sformatf("REF: Wrote 0x%0h to 0x%0h", pwdata, paddr));
                end
            end
        end
    end

    //========================================================================
    // TRANSACTION CAPTURE AND SELF-CHECKING
    //========================================================================
    // Captures every APB transaction and performs automatic verification.
    // Compares DUT outputs against the reference model.
    //
    // This is the CORE of the self-checking testbench.
    //========================================================================
    
    always @(posedge pclk) begin
        // Trigger on transaction completion (PENABLE=1, PREADY=1)
        if (penable && pready) begin
            score_total = score_total + 1;
            
            // Record transaction details
            current_pwrite = pwrite;
            current_paddr = paddr;
            current_pwdata = pwdata;
            current_pslverr = pslverr;
            current_checked = 1'b0;
            
            //================================================================
            // WRITE OPERATION VERIFICATION
            //================================================================
            if (pwrite && !pslverr) begin
                if (paddr < 8'h80) begin
                    // Valid Write - Check memory content
                    if (dut.slave1_inst.memory[paddr] == pwdata) begin
                        log_message(`LOG_INFO, $sformatf("✅ WRITE PASS: 0x%0h = 0x%0h", paddr, pwdata));
                        score_pass = score_pass + 1;
                        current_passed = 1'b1;
                        current_checked = 1'b1;
                        current_prdata = 8'h00;
                    end else begin
                        log_message(`LOG_ERROR, $sformatf("WRITE FAIL: Expected 0x%0h at 0x%0h, Got 0x%0h", 
                                   pwdata, paddr, dut.slave1_inst.memory[paddr]));
                        score_fail = score_fail + 1;
                        current_passed = 1'b0;
                        current_checked = 1'b1;
                        current_prdata = 8'h00;
                    end
                end
                else begin
                    // Invalid Address Write - Should generate error
                    if (pslverr) begin
                        log_message(`LOG_INFO, $sformatf("✅ ERROR PASS: 0x%0h invalid", paddr));
                        score_pass = score_pass + 1;
                        current_passed = 1'b1;
                        current_checked = 1'b1;
                        current_prdata = 8'h00;
                    end else begin
                        log_message(`LOG_ERROR, $sformatf("INVALID WRITE FAIL: 0x%0h should have errored", paddr));
                        score_fail = score_fail + 1;
                        current_passed = 1'b0;
                        current_checked = 1'b1;
                        current_prdata = 8'h00;
                    end
                end
                // Clear any pending read on write
                read_pending = 1'b0;
                pending_check_done = 1'b0;
            end
            
            //================================================================
            // READ OPERATION VERIFICATION - Pipeline Aware
            //================================================================
            else if (!pwrite && !pslverr) begin
                if (paddr < 8'h80) begin
                    // Valid Read - Set up pending check for pipeline delay
                    // The read data will be available after READ_PIPELINE_DELAY cycles
                    read_pending = 1'b1;
                    pending_addr = paddr;
                    pending_data = ref_memory[paddr];
                    pipeline_cnt = 2'b0;
                    pending_check_done = 1'b0;
                    current_passed = 1'b0;
                    current_checked = 1'b0;
                    log_message(`LOG_DEBUG, $sformatf("READ pending: addr=0x%0h, expected=0x%0h", 
                               paddr, ref_memory[paddr]));
                end
                else begin
                    // Invalid Address Read - Should generate error
                    if (pslverr) begin
                        log_message(`LOG_INFO, $sformatf("✅ ERROR PASS: 0x%0h invalid", paddr));
                        score_pass = score_pass + 1;
                        current_passed = 1'b1;
                        current_checked = 1'b1;
                        current_prdata = 8'h00;
                    end else begin
                        log_message(`LOG_ERROR, $sformatf("INVALID READ FAIL: 0x%0h should have errored", paddr));
                        score_fail = score_fail + 1;
                        current_passed = 1'b0;
                        current_checked = 1'b1;
                        current_prdata = 8'h00;
                    end
                    read_pending = 1'b0;
                end
            end
            
            //================================================================
            // ERROR CONDITION VERIFICATION
            //================================================================
            else if (pslverr) begin
                if (paddr >= 8'h80) begin
                    log_message(`LOG_INFO, $sformatf("✅ ERROR PASS: 0x%0h correctly invalid", paddr));
                    score_pass = score_pass + 1;
                    current_passed = 1'b1;
                    current_checked = 1'b1;
                    current_prdata = 8'h00;
                end else begin
                    log_message(`LOG_ERROR, $sformatf("ERROR FAIL: Unexpected error at valid address 0x%0h", paddr));
                    score_fail = score_fail + 1;
                    current_passed = 1'b0;
                    current_checked = 1'b1;
                    current_prdata = 8'h00;
                end
                read_pending = 1'b0;
                pending_check_done = 1'b0;
            end
            
            //================================================================
            // STORE TRANSACTION IN HISTORY
            //================================================================
            if (trans_index < 256) begin
                trans_pwrite[trans_index] = current_pwrite;
                trans_paddr[trans_index] = current_paddr;
                trans_pwdata[trans_index] = current_pwdata;
                trans_prdata[trans_index] = current_prdata;
                trans_pslverr[trans_index] = current_pslverr;
                trans_passed[trans_index] = current_passed;
                trans_checked[trans_index] = current_checked;
                trans_index = trans_index + 1;
            end
        end
    end

    //========================================================================
    // PENDING READ CHECK - Pipeline Delay Handling
    //========================================================================
    // Verifies read data after the pipeline delay has elapsed.
    // This is CRITICAL for correct read verification with pipelined RTL.
    //
    // The master's read data output (apb_read_data_out) is delayed by
    // READ_PIPELINE_DELAY cycles. This process waits for the delay and
    // then verifies the data.
    //========================================================================
    
    always @(posedge pclk or negedge presetn) begin
        if (!presetn) begin
            read_pending <= 1'b0;
            pipeline_cnt <= 2'b0;
            pending_check_done <= 1'b0;
            pending_addr <= 8'h00;
            pending_data <= 8'h00;
        end
        else begin
            if (read_pending && !pending_check_done) begin
                // Wait for pipeline delay
                if (pipeline_cnt < READ_PIPELINE_DELAY - 1) begin
                    pipeline_cnt <= pipeline_cnt + 1;
                end
                else begin
                    // Pipeline delay complete - Check data now
                    if (apb_read_data_out == pending_data) begin
                        log_message(`LOG_INFO, $sformatf("✅ READ PASS: 0x%0h = 0x%0h (pipeline check)", 
                                   pending_addr, apb_read_data_out));
                        score_pass = score_pass + 1;
                        if (trans_index > 0) begin
                            trans_passed[trans_index-1] = 1'b1;
                            trans_checked[trans_index-1] = 1'b1;
                            trans_prdata[trans_index-1] = apb_read_data_out;
                        end
                    end else begin
                        log_message(`LOG_ERROR, $sformatf("READ FAIL: Expected 0x%0h at 0x%0h, Got 0x%0h", 
                                   pending_data, pending_addr, apb_read_data_out));
                        score_fail = score_fail + 1;
                        if (trans_index > 0) begin
                            trans_passed[trans_index-1] = 1'b0;
                            trans_checked[trans_index-1] = 1'b1;
                            trans_prdata[trans_index-1] = apb_read_data_out;
                        end
                    end
                    read_pending <= 1'b0;
                    pending_check_done <= 1'b1;
                    pipeline_cnt <= 2'b0;
                end
            end
        end
    end

    //========================================================================
    // WAIT FOR STABLE IDLE
    //========================================================================
    // Waits for the FSM to be in a stable IDLE state before starting
    // a new transaction. This prevents "Transfer during active
    // transaction" warnings.
    //
    // The task waits for idle_stable to be asserted, with a timeout.
    // After the wait, 2 extra cycles are added for stabilization.
    //========================================================================
    
    task wait_for_idle;
        integer timeout;
        begin
            timeout = 0;
            // Wait for stable IDLE
            while (!idle_stable && timeout < TIMEOUT_CYCLES*2) begin
                @(posedge pclk);
                timeout = timeout + 1;
            end
            
            // Report warning if timeout occurred
            if (timeout == TIMEOUT_CYCLES*2) begin
                log_message(`LOG_WARNING, "Timeout waiting for stable IDLE");
                score_warnings = score_warnings + 1;
            end
            
            // Extra stabilization cycles
            repeat (2) @(posedge pclk);
            #(CLK_PERIOD/2);
        end
    endtask

    //========================================================================
    // WAIT FOR PENDING READ COMPLETION
    //========================================================================
    // Waits for any pending read verification to complete.
    // This ensures read verification is not interrupted by the next
    // transaction.
    //========================================================================
    
    task wait_for_pending_read;
        integer timeout;
        begin
            timeout = 0;
            // Wait for pending read to complete
            while (read_pending && timeout < TIMEOUT_CYCLES*2) begin
                @(posedge pclk);
                timeout = timeout + 1;
            end
            
            // Report warning if timeout occurred
            if (read_pending) begin
                log_message(`LOG_WARNING, $sformatf("Pending read at 0x%0h still pending", pending_addr));
                score_warnings = score_warnings + 1;
                read_pending = 1'b0;
                pending_check_done = 1'b1;
            end
        end
    endtask

    //========================================================================
    // TRANSFER COMPLETION WAIT
    //========================================================================
    // Waits for an APB transaction to complete.
    // Handles both read and write operations with appropriate delays.
    //
    // Steps:
    //   1. Wait for ENABLE phase (penable=1)
    //   2. Wait for PREADY (pready=1)
    //   3. If read, wait for pipeline delay and pending read check
    //   4. If write, wait one extra cycle
    //
    // Icarus Note: Uses 'done' flag instead of 'return' statement
    // because Icarus has issues with return in tasks.
    //========================================================================
    
    task wait_for_transfer_completion;
        integer timeout;
        integer done;
        begin
            timeout = 0;
            done = 0;
            
            // Wait for ENABLE phase
            while (!penable && timeout < TIMEOUT_CYCLES) begin
                @(posedge pclk);
                timeout = timeout + 1;
            end
            
            if (timeout == TIMEOUT_CYCLES) begin
                log_message(`LOG_ERROR, "Timeout waiting for ENABLE");
                score_fail = score_fail + 1;
                done = 1;
            end
            
            if (!done) begin
                // Wait for PREADY
                timeout = 0;
                while (!pready && timeout < TIMEOUT_CYCLES) begin
                    @(posedge pclk);
                    timeout = timeout + 1;
                end
                
                if (timeout == TIMEOUT_CYCLES) begin
                    log_message(`LOG_ERROR, "Timeout waiting for PREADY");
                    score_fail = score_fail + 1;
                    done = 1;
                end
            end
            
            if (!done) begin
                // Handle pipeline delay for reads
                if (!pwrite) begin
                    // Wait for pipeline delay + 1 cycle
                    repeat (READ_PIPELINE_DELAY + 1) begin
                        @(posedge pclk);
                        #1;
                    end
                    // Wait for pending read check to complete
                    wait_for_pending_read();
                end else begin
                    // For writes, one extra cycle is sufficient
                    @(posedge pclk);
                    #1;
                end
            end
        end
    endtask

    //========================================================================
    // TEST HELPER TASKS - Directed Stimulus Generation
    //========================================================================
    // These tasks generate specific directed transactions.
    // Each task performs a complete transaction (setup, execute, verify).
    //========================================================================
    
    //------------------------------------------------------------------------
    // WRITE TEST
    //------------------------------------------------------------------------
    // Performs a single write operation:
    //   1. Wait for IDLE state
    //   2. Assert transfer and write signals
    //   3. Provide address and data
    //   4. Wait for transaction completion
    //   5. Verify via scoreboard (automatic in transaction capture)
    //------------------------------------------------------------------------
    task write_test;
        input [7:0] addr;
        input [7:0] data;
        begin
            wait_for_idle();  // Wait for stable IDLE
            
            log_message(`LOG_INFO, $sformatf("WRITE 0x%0h=0x%0h", addr, data));
            
            // Assert transfer signals
            transfer = 1; write = 1; read = 0;
            apb_write_paddr = addr;
            apb_write_data = data;
            
            // Wait for one clock edge before checking
            @(posedge pclk);
            
            // Wait for transaction completion
            wait_for_transfer_completion();
            
            // Deassert transfer signals
            transfer = 0; write = 0;
            
            // Wait for IDLE and extra delay
            wait_for_idle();
            #(CLK_PERIOD*2);
        end
    endtask
    
    //------------------------------------------------------------------------
    // READ TEST
    //------------------------------------------------------------------------
    // Performs a single read operation:
    //   1. Wait for IDLE state
    //   2. Assert transfer and read signals
    //   3. Provide address
    //   4. Wait for transaction completion (includes pipeline delay)
    //   5. Verify via scoreboard (automatic in pending read check)
    //------------------------------------------------------------------------
    task read_test;
        input [7:0] addr;
        begin
            wait_for_idle();  // Wait for stable IDLE
            
            log_message(`LOG_INFO, $sformatf("READ 0x%0h", addr));
            
            // Assert transfer signals
            transfer = 1; read = 1; write = 0;
            apb_read_paddr = addr;
            
            // Wait for one clock edge before checking
            @(posedge pclk);
            
            // Wait for transaction completion (includes pipeline delay)
            wait_for_transfer_completion();
            
            // Deassert transfer signals
            transfer = 0; read = 0;
            
            // Wait for IDLE and extra delay
            wait_for_idle();
            #(CLK_PERIOD*2);
        end
    endtask
    
    //------------------------------------------------------------------------
    // WRITE-READ TEST
    //------------------------------------------------------------------------
    // Performs a write followed by a read to the same address.
    // This is a common pattern to verify read-after-write functionality.
    //------------------------------------------------------------------------
    task write_read_test;
        input [7:0] addr;
        input [7:0] data;
        begin
            log_message(`LOG_INFO, $sformatf("WRITE-READ 0x%0h", addr));
            write_test(addr, data);  // Write first
            read_test(addr);          // Then read back
        end
    endtask
    
    //------------------------------------------------------------------------
    // BURST WRITE TEST
    //------------------------------------------------------------------------
    // Performs multiple consecutive write operations to sequential addresses.
    // Useful for testing throughput and back-to-back transactions.
    //------------------------------------------------------------------------
    task burst_write_test;
        input [7:0] start_addr;
        input [7:0] data_pattern;
        input [3:0] count;
        integer i;
        begin
            log_message(`LOG_INFO, $sformatf("BURST WRITE %0d addresses from 0x%0h", count, start_addr));
            for (i = 0; i < count; i = i + 1) begin
                write_test(start_addr + i, data_pattern + i);
                #(CLK_PERIOD*2);
            end
        end
    endtask
    
    //------------------------------------------------------------------------
    // BURST READ TEST
    //------------------------------------------------------------------------
    // Performs multiple consecutive read operations from sequential addresses.
    // Useful for testing throughput and back-to-back transactions.
    //------------------------------------------------------------------------
    task burst_read_test;
        input [7:0] start_addr;
        input [3:0] count;
        integer i;
        begin
            log_message(`LOG_INFO, $sformatf("BURST READ %0d addresses from 0x%0h", count, start_addr));
            for (i = 0; i < count; i = i + 1) begin
                read_test(start_addr + i);
                #(CLK_PERIOD*2);
            end
        end
    endtask

    //========================================================================
    // RUNTIME PROTOCOL MONITORING
    //========================================================================
    // Continuously monitors the APB bus for protocol violations.
    // Detects:
    //   1. Multiple PSELs active simultaneously
    //   2. Transfer request during active transaction
    //========================================================================
    
    reg prev_transfer;  // Previous transfer value for edge detection
    
    initial begin
        prev_transfer = 1'b0;
    end
    
    always @(posedge pclk) begin
        // Protocol Check 1: Multiple PSELs active
        if (psel1 && psel2 && penable) begin
            log_message(`LOG_ERROR, "Protocol violation: Multiple PSELs active");
            score_fail = score_fail + 1;
        end
        
        // Protocol Check 2: Transfer during active transaction
        if (transfer && (master_state_comb == ENABLE) && !pready) begin
            if (transfer && !prev_transfer) begin
                log_message(`LOG_WARNING, "Transfer request during active transaction");
                score_warnings = score_warnings + 1;
            end
            prev_transfer = transfer;
        end
    end

    //========================================================================
    // FINAL PENDING READ CHECK
    //========================================================================
    // Checks for any pending reads at the end of simulation.
    // Ensures all reads have been verified.
    //========================================================================
    
    task check_pending_reads;
        begin
            if (read_pending && !pending_check_done) begin
                log_message(`LOG_WARNING, $sformatf("Final pending read at 0x%0h", pending_addr));
                if (apb_read_data_out == pending_data) begin
                    log_message(`LOG_INFO, $sformatf("✅ FINAL READ PASS: 0x%0h = 0x%0h", 
                               pending_addr, apb_read_data_out));
                    score_pass = score_pass + 1;
                end else begin
                    log_message(`LOG_ERROR, $sformatf("FINAL READ FAIL: Expected 0x%0h, Got 0x%0h", 
                               pending_data, apb_read_data_out));
                    score_fail = score_fail + 1;
                end
                read_pending = 1'b0;
                pending_check_done = 1'b1;
            end
        end
    endtask

    //========================================================================
    // TRANSACTION DISPLAY TASK
    //========================================================================
    // Displays detailed transaction information for a given index.
    // Used for debugging and failure analysis.
    //========================================================================
    
    task display_transaction;
        input integer index;
        begin
            $display("==================================================");
            $display("Transaction #%0d", index);
            $display("  Type     : %s", trans_pwrite[index] ? "WRITE" : "READ");
            $display("  Address  : 0x%02h", trans_paddr[index]);
            if (trans_pwrite[index])
                $display("  Data     : 0x%02h", trans_pwdata[index]);
            else
                $display("  Data     : 0x%02h", trans_prdata[index]);
            $display("  Error    : %s", trans_pslverr[index] ? "YES" : "NO");
            $display("  Checked  : %s", trans_checked[index] ? "YES" : "NO");
            $display("  Result   : %s", trans_passed[index] ? "✅ PASS" : "❌ FAIL");
            $display("==================================================");
        end
    endtask

    //========================================================================
    // MAIN TEST SEQUENCE - DIRECTED TESTS
    //========================================================================
    // This is the main test sequence that runs the directed tests.
    // It is organized into test groups, each targeting specific
    // functionality.
    //
    // The tests are DIRECTED (specific, predetermined) rather than random.
    // This makes the testbench deterministic and reproducible.
    //========================================================================
    
    initial begin
        // Local variables
        integer i;
        integer start_time, end_time;
        
        //============================================================
        // TESTBENCH HEADER
        //============================================================
        $display("\n--------------------------------------------------");
        $display("--     APB DIRECTED VERIFICATION TEST SUITE      --");
        $display("--   Self-Checking | Directed | Icarus Compatible --");
        $display("----------------------------------------------------");
        $display("Clock Period: %0d ns", CLK_PERIOD);
        $display("Timeout: %0d cycles", TIMEOUT_CYCLES);
        $display("Read Pipeline Delay: %0d cycles", READ_PIPELINE_DELAY);
        $display("------------------------------------------------------\n");

        //============================================================
        // SYSTEM RESET
        //============================================================
        log_message(`LOG_INFO, "Applying Reset");
        presetn = 0;
        transfer = 0; read = 0; write = 0;
        read_pending = 0; pending_check_done = 0; pipeline_cnt = 0;

        #(CLK_PERIOD*2) presetn = 1;
        #(CLK_PERIOD*5);  // Extended reset recovery
        log_message(`LOG_INFO, "Reset Complete");
        wait_for_idle();

        //============================================================
        // TEST GROUP 1: Basic Functionality
        //============================================================
        // Purpose: Verify basic read and write operations.
        // Tests:  Write, Read, Write-Read, Multiple writes/reads
        //============================================================
        $display("\n-----------------------------------------");
        $display("  TEST GROUP 1: Basic Functionality");
        $display("---------------------------------------------\n");
        
        // Test 1.1: Simple Write
        write_test(8'h10, 8'hAA);
        
        // Test 1.2: Simple Read (should read back 0xAA)
        read_test(8'h10);
        
        // Test 1.3: Write-Read to different address
        write_read_test(8'h20, 8'h55);
        
        // Test 1.4: Multiple Writes to different addresses
        for (i = 0; i < 4; i = i + 1) begin
            write_test(8'h30 + i, 8'hAA + i);
        end
        
        // Test 1.5: Read all written addresses
        for (i = 0; i < 4; i = i + 1) begin
            read_test(8'h30 + i);
        end

        //============================================================
        // TEST GROUP 2: Error & Boundary Conditions
        //============================================================
        // Purpose: Verify error handling and boundary conditions.
        // Tests:  Invalid addresses, boundary addresses, zero address
        //============================================================
        $display("\n-------------------------------------------");
        $display("  TEST GROUP 2: Error & Boundary Conditions");
        $display("------------------------------------------------\n");
        
        // Test 2.1: Write to invalid address (0x80)
        write_test(8'h80, 8'h55);
        
        // Test 2.2: Read from invalid address (0x80)
        read_test(8'h80);
        
        // Test 2.3: Last valid address (0x7F)
        write_read_test(8'h7F, 8'hFF);
        
        // Test 2.4: Max address (0xFF) - should error
        write_test(8'hFF, 8'h00);
        
        // Test 2.5: Zero address (0x00)
        write_read_test(8'h00, 8'h12);

        //============================================================
        // TEST GROUP 3: Stress & Corner Cases
        //============================================================
        // Purpose: Verify throughput and corner cases.
        // Tests:  Burst writes/reads, data patterns, alternating patterns
        //============================================================
        $display("\n-----------------------------------------");
        $display("  TEST GROUP 3: Stress & Corner Cases");
        $display("---------------------------------------------\n");
        
        // Test 3.1: Burst write 8 addresses
        burst_write_test(8'h40, 8'hA0, 8);
        
        // Test 3.2: Burst read same 8 addresses
        burst_read_test(8'h40, 8);
        
        // Test 3.3: Write with max data value (0xFF)
        write_read_test(8'h50, 8'hFF);
        
        // Test 3.4: Write with min data value (0x00)
        write_read_test(8'h51, 8'h00);
        
        // Test 3.5: Alternating write/read pattern
        for (i = 0; i < 5; i = i + 1) begin
            write_test(8'h60 + i, 8'hB0 + i);
            read_test(8'h60 + i);
        end

        //============================================================
        // TEST GROUP 4: Reset Recovery Tests
        //============================================================
        // Purpose: Verify proper recovery from reset conditions.
        // Tests:  Reset during transaction, reset then transaction,
        //         multiple resets
        //============================================================
        $display("\n--------------------------------------------");
        $display("  TEST GROUP 4: Reset Recovery");
        $display("--------------------------------------------\n");
        
        // Test 4.1: Reset during transaction
        log_message(`LOG_INFO, "Starting: Reset During Transaction");
        transfer = 1; write = 1;
        apb_write_paddr = 8'h70;
        apb_write_data = 8'hAA;
        @(posedge pclk);
        #(CLK_PERIOD/2) presetn = 0;  // Assert reset mid-transaction
        #(CLK_PERIOD*3) presetn = 1;   // Release reset
        #(CLK_PERIOD*5);
        transfer = 0; write = 0;
        log_message(`LOG_INFO, "Reset During Transaction Complete");
        wait_for_idle();
        
        // Test 4.2: Reset then transaction
        log_message(`LOG_INFO, "Starting: Reset then Transaction");
        presetn = 0;
        #(CLK_PERIOD*2) presetn = 1;
        #(CLK_PERIOD*5);
        wait_for_idle();
        write_read_test(8'h75, 8'hBB);
        
        // Test 4.3: Multiple reset cycles
        for (i = 0; i < 3; i = i + 1) begin
            log_message(`LOG_INFO, $sformatf("Reset Cycle %0d", i+1));
            presetn = 0;
            #(CLK_PERIOD*2) presetn = 1;
            #(CLK_PERIOD*5);
            wait_for_idle();
            write_read_test(8'h78 + i, 8'hCC + i);
        end

        //============================================================
        // TEST GROUP 5: Performance Measurement
        //============================================================
        // Purpose: Measure transaction timing/throughput.
        // Tests:  Repeated writes to measure average transaction time
        //============================================================
        $display("\n--------------------------------------------");
        $display("  TEST GROUP 5: Performance Measurement");
        $display("--------------------------------------------\n");
        
        log_message(`LOG_INFO, "Starting: Performance Measurement");
        
        // Record start time
        start_time = $time;
        
        // Perform 50 write operations
        for (i = 0; i < 50; i = i + 1) begin
            write_test(8'h7A + (i % 5), 8'hDD + i);
            #(CLK_PERIOD);
        end
        
        // Record end time
        end_time = $time;
        
        // Display performance metrics
        $display("Performance: %0d writes in %0d ns", 50, end_time - start_time);
        $display("Average: %0d ns per write", (end_time - start_time) / 50);

        //============================================================
        // FINAL REPORT
        //============================================================
        #(CLK_PERIOD*5);
        check_pending_reads();
        #(CLK_PERIOD*2);
        
        $display("\n--------------------------------------------");
        $display("║           FINAL TEST SUMMARY                  ║");
        $display("--------------------------------------------");
        $display("║  Total Tests  : %8d                         ║", score_total);
        $display("║  Passed       : %8d ✅                      ║", score_pass);
        $display("║  Failed       : %8d                         ║", score_fail);
        $display("║  Warnings     : %8d                         ║", score_warnings);
        $display("║  Pass Rate    : %8.1f%%                     ║", 
                 (score_total > 0) ? (score_pass * 100.0 / score_total) : 0);
        $display("--------------------------------------------");
        
        // Overall result
        if (score_fail == 0) begin
            $display("║  ✅ ALL TESTS PASSED                       ║");
        end else begin
            $display("║  ❌ TESTS FAILED - Check Error Log         ║");
        end
        
        // Warning status
        if (score_warnings == 0) begin
            $display("║  ✅ NO WARNINGS                            ║");
        end else begin
            $display("║  ⚠️  %0d WARNINGS - Review Log         ║", score_warnings);
        end
        
        $display("--------------------------------------------");
        
        // Display failures if DEBUG_LEVEL >= 2
        if (DEBUG_LEVEL >= 2 && score_fail > 0) begin
            $display("\nTransaction History (Failures Only):");
            for (i = 0; i < trans_index && i < 256; i = i + 1) begin
                if (!trans_passed[i] && trans_checked[i]) begin
                    display_transaction(i);
                end
            end
        end
        
        #(CLK_PERIOD*5);
        $finish;
    end

    //========================================================================
    // WAVEFORM DUMP
    //========================================================================
    // Generates a VCD file for waveform viewing.
    // Enabled when DEBUG_LEVEL >= 1.
    //
    // View with: gtkwave apb_sim.vcd
    //========================================================================
    
    initial begin
        if (DEBUG_LEVEL >= 1) begin
            $dumpfile("apb_sim.vcd");
            $dumpvars(0, testbench);
            log_message(`LOG_DEBUG, "Waveform dumping enabled");
        end
    end

endmodule
